CREATE SCHEMA MYDB;

CREATE TABLE MYDB.CAR (
        ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
        BRAND VARCHAR(255) NOT NULL,
        MODEL VARCHAR(255),
        VERSION INTEGER,
        PRIMARY KEY (ID)
);

INSERT INTO MYDB.CAR (BRAND, MODEL, VERSION) VALUES ('BMW', '320d', 1);
INSERT INTO MYDB.CAR (BRAND, MODEL) VALUES ('Audi', 'A3 2.0 TDI');
INSERT INTO MYDB.CAR (BRAND, MODEL) VALUES ('Mercedes', 'A 220d');